api_key:
  key: "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"
model:
  name:  "gpt-4o" #"gpt-3.5-turbo" #"gpt-4o"   "gpt-4o"  "gpt-3.5-turbo"  "o3-mini" "o1-mini"

